### ISSUE TITLE
Ability to configure user request funtionality

### ISSUE THREAD

**Issue by josmilan** [decentralised-dataexchange/bb-consent-ios-privacy-dashboard#10]
In the mobile UI, we need the ability to turn off user requests via configuration. This means that if someone only needs the privacy dashboard, it shall be possible.

- Delete my data
- Download my data

Default: Data request will be disabled.

**Comment by Mumthasir-vp** [comment]
https://github.com/decentralised-dataexchange/bb-consent-ios-privacy-dashboard/issues/46
