### ISSUE TITLE
With Disallow, the toggle button is On 

### ISSUE THREAD

**Issue by kashishmalik** [decentralised-dataexchange/bb-consent-ios-privacy-dashboard#180]
With Disallow, the toggle button is On 

![Screenshot 2023-11-16 at 23 29 36](https://github.com/decentralised-dataexchange/bb-consent-ios-privacy-dashboard/assets/92527972/23a7926c-763d-49a9-8e03-5fd160c464db)

**Comment by Mumthasir-vp** [comment]
@kashishmalik Any special scenario for this, it is showing fine for me. Can you try by uninstalling the previous build?

<img width="464" alt="Screenshot 2023-11-17 at 3 10 16 PM" src="https://github.com/decentralised-dataexchange/bb-consent-ios-privacy-dashboard/assets/134942402/977fab9f-1e01-433a-89b7-b51351d51458">
