### ISSUE TITLE
Consent status is shown as disabled when the switch is enabled

### ISSUE THREAD

**Issue by josmilan** [decentralised-dataexchange/bb-consent-ios-privacy-dashboard#229]
![WhatsApp Image 2024-04-10 at 15 33 25_1dd59a49](https://github.com/decentralised-dataexchange/bb-consent-ios-privacy-dashboard/assets/20550674/c0d34dd6-7fa1-49df-8f35-8e7609c24d14)

**Comment by georgepadayatti** [comment]
Steps to reproduce:

1. Create a data agreement with lawful basis - contract and publish it.
2. As an individual, when the privacy dashboard is opened, it will be allowed(toggled on) and caption text will Allow n of n
3. Organisation admin edits the data agreement and changes the lawful basis to consent and publishes it.
4. Individual disallow the data agreement from the privacy dashboard (toggle off)
5. Organisation admin edits the data agreement and changes the lawful basis to contract again and publishes it.
6. This time, when the individual open the privacy dashboard the toggle is turned ON, but the caption text stay in DISALLOW.

**Comment by georgepadayatti** [comment]
> Steps to reproduce:
> 
> 1. Create a data agreement with lawful basis - contract and publish it.
> 2. As an individual, when the privacy dashboard is opened, it will be allowed(toggled on) and caption text will Allow n of n
> 3. Organisation admin edits the data agreement and changes the lawful basis to consent and publishes it.
> 4. Individual disallow the data agreement from the privacy dashboard (toggle off)
> 5. Organisation admin edits the data agreement and changes the lawful basis to contract again and publishes it.
> 6. This time, when the individual open the privacy dashboard the toggle is turned ON, but the caption text stay in DISALLOW.

@lalc This was the issue you encountered. We will fix this in the next update.

**Comment by Mumthasir-vp** [comment]
@georgepadayatti Thank you for providing the clear steps. After following them, I noticed that the `optIn` property in the records API response for the contract type is returning 'false' instead of 'true'. This is affecting some of the conditional flows, resulting in it displaying as 'DISALLOW'.
