### ISSUE TITLE
Logo image and Cover image is not getting loaded

### ISSUE THREAD

**Issue by josmilan** [decentralised-dataexchange/bb-consent-ios-privacy-dashboard#40]

**Comment by Mumthasir-vp** [comment]
@josmilan  you meant, Logo image and Cover image is getting 'not' loaded, right ?

**Comment by josmilan** [comment]
Yes

**Comment by Mumthasir-vp** [comment]
This issue is fixed with this [commit](https://github.com/decentralised-dataexchange/bb-consent-ios-privacy-dashboard/pull/52/commits/114e4a368589652c18ce0d0e76a5b8d245da9e98).
