### ISSUE TITLE
In consent history and user request dates should match with the android

### ISSUE THREAD

**Issue by josmilan** [decentralised-dataexchange/bb-consent-ios-privacy-dashboard#41]
![WhatsApp Image 2023-09-29 at 12 38 35](https://github.com/decentralised-dataexchange/bb-consent-ios-privacy-dashboard/assets/20550674/65afbe60-af14-40d6-aff0-e3caaeb8f3ae)

**Comment by Mumthasir-vp** [comment]
This issue is fixed with this [commit](https://github.com/decentralised-dataexchange/bb-consent-ios-privacy-dashboard/pull/52/commits/114e4a368589652c18ce0d0e76a5b8d245da9e98).
