### ISSUE TITLE
Not able to add new user requests

### ISSUE THREAD

**Issue by josmilan** [decentralised-dataexchange/bb-consent-ios-privacy-dashboard#42]
When we click "+" button, and adding request, nothing gets added

**Comment by Mumthasir-vp** [comment]
This issue fixed on this [commit](https://github.com/decentralised-dataexchange/bb-consent-ios-privacy-dashboard/pull/58/commits/1f9d86d7db3c622e679a7ac0ae849386fdf5db03).
