### ISSUE TITLE
Remove Disallow all button from attribute listing screen

### ISSUE THREAD

**Issue by josmilan** [decentralised-dataexchange/bb-consent-ios-privacy-dashboard#48]
![WhatsApp Image 2023-09-29 at 13 01 23](https://github.com/decentralised-dataexchange/bb-consent-ios-privacy-dashboard/assets/20550674/6ff8d3ad-0b4c-47dc-a646-e76dba36d3d9)

**Comment by Mumthasir-vp** [comment]
This is done with this [commit](https://github.com/decentralised-dataexchange/bb-consent-ios-privacy-dashboard/pull/52/commits/114e4a368589652c18ce0d0e76a5b8d245da9e98).
