### ISSUE TITLE
Status bar is different throughout the app.

### ISSUE THREAD

**Issue by josmilan** [decentralised-dataexchange/bb-consent-ios-privacy-dashboard#50]
Make the status bar the same throughout the app, at least the internal screens, other than dashboard

- [x] the items in the status bar should be visible also

**Comment by Mumthasir-vp** [comment]
This issue if fixed with this [commit](https://github.com/decentralised-dataexchange/bb-consent-ios-privacy-dashboard/pull/52/commits/114e4a368589652c18ce0d0e76a5b8d245da9e98).
