### ISSUE TITLE
Description and other details for cocoapod

### ISSUE THREAD

**Issue by Mumthasir-vp** [decentralised-dataexchange/bb-consent-ios-privacy-dashboard#61]
Description and other details for iOS [cocoapod portal](https://cocoapods.org/pods/PrivacyDashboardiOS)

- [x] Summary
A short description of PrivacyDashboardiOS 
- [x] Description
This description is used to generate tags and improve search results
- [ ]  Screenshots
uploaded url
- [x] Social_media_url
- [x] Author

Note: None of the above are mandatory.

**Comment by georgepadayatti** [comment]
@Mumthasir-vp Can we change the author to iGrant.io and email to support@igrant.io


![2023-10-30_16-48](https://github.com/decentralised-dataexchange/bb-consent-ios-privacy-dashboard/assets/16397960/3313717a-6102-4dab-ba9e-38aa27be3ad9)

**Comment by Mumthasir-vp** [comment]
Yes sure, only we need is a verification from our support mail.

**Comment by georgepadayatti** [comment]
> Yes sure, only we need is a verification from our support mail.

Yes I can fix it.

**Comment by georgepadayatti** [comment]
> Description and other details for iOS [cocoapod portal](https://cocoapods.org/pods/PrivacyDashboardiOS)
> 
> * [ ]  Summary
>   A short description of PrivacyDashboardiOS
> * [ ]  Description
>   This description is used to generate tags and improve search results
> * [ ]   Screenshots
>   uploaded url
> * [ ]  Social_media_url
> * [ ]  Author
> 
> Note: None of the above are mandatory.

@kashishmalik @lalc Appreciate your inputs on this.

**Comment by lalc** [comment]
Here is my input:

**Summary**
Govstack PrivacyDashboard SDKs – Effortlessly embed a comprehensive privacy dashboard into any mobile application out of the box, ensuring adherence to Govstack's consent management framework. Prioritise user trust and transparency with this seamless integration tool.

**Description**
This SDKS is developed to provide an out-of-the-box privacy dashboard feature based on the Govstack consent building block framework. It is designed to integrate seamlessly into mobile applications; the dashboard provides a transparent view of how user data is utilised. Using data agreements, users and developers are kept informed about data procedures. Individual users can monitor their data usage, whilst developers are guided to handle the data appropriately, all by the Govstack consent management framework.

Tags: #Transparency, #DataUse, #DataAgreements, #Govstack, #PrivacyDashboard, #BritishEnglish, #MobileIntegration, #ConsentManagement.

**Screenshots**: Please provide me with the latest screenshots, and I can add them in an iPhone frame

**Uploaded url:** ??? _Still trying to figure out what is needed here? @georgepadayatti ? 

**Social_media_url**: https://www.linkedin.com/company/igrantio
**Author**: iGrant.io, Sweden

**Comment by Mumthasir-vp** [comment]
> **Uploaded url:** ??? _Still trying to figure out what is needed here? @georgepadayatti ?
It is screenshots uploaded url.

**Comment by georgepadayatti** [comment]
Guess we can avoid this if not mandatory ?

**Comment by georgepadayatti** [comment]
> Yes it is optional only.

Closing the issue as we have updated metdata
